### ISSUE TITLE
Add clearer installation / usage instructions

### ISSUE THREAD

**Issue by alichtman** [manilarome/rofi-spotlight#6]
Can you include some instructions for installing this? It's unclear exactly what a user should do.

EDIT: nvm, just found them. Maybe just explain the link between the python and bash scripts more clearly?

**Comment by eromatiya** [comment]
>  Maybe just explain the link between the python and bash scripts more clearly?

The python script's file name's the clue - it handles the web search stuff. While the `rofi-spotlight.sh` handles all the search query (it passes the query to the python script if the query has a certain pattern - read README) and file search.

**Comment by alichtman** [comment]
Yeah, totally understood. I'm just telling you that it wasn't immediately obvious to me how to install / use this, and that it might be worth improving the docs. 

- Here's what each file does
- Here's where they have to live (in relation to each other? Are you using $PATH to find them?, etc)
- etc

I can find out all these answers on my own by reading the source, but I don't have the time to do so right now, so I just put using this script on my backlog.

**Comment by eromatiya** [comment]
I didn't add an instruction of how to install it because I felt that there's no need for it. It's just:

1. Clone it.
2. Run it by `rofi -modi "Global Search":"rofi-spotlight/rofi-spotlight.sh" -show "Global Search" \
-config rofi-spotlight/rofi.rasi`.

Yes. I just assumed that everyone knew how to clone/download a repo. So yeah lol

> Here's what each file does

Yeah, didn't think about explaining the files. Will add it to the docs.

> Here's where they have to live (in relation to each other? Are you using $PATH to find them?, etc)

You can add the script to the $PATH or not. The path to script must be in the rofi command.

Anyway yeah the documentation needs an improvement but I don't really have time right now. Patches welcome, of course! Thank you for your input! Closing this for now.
